llm:
  model: mistral:latest
  base_url: http://localhost:11434

agents:
  researcher:
    role: Researcher
    goal: Research the topic thoroughly and provide structured findings.
    backstory: You are an expert Python educator and researcher.

  writer:
    role: Writer
    goal: Write easy-to-understand and engaging tutorials from research.
    backstory: You specialize in writing Python content for beginners.

  reviewer:
    role: Reviewer
    goal: Refine tutorials for clarity, grammar, and educational quality.
    backstory: You are a senior editor and content reviewer.
